export const data = [
    {
    img : require("./assets/esp.png"),
    title:'spain Ibiza ',
    desc :'5 Star hotel',
    reveiw:4.98,
    price:150,
    date :'25-2nov',
    },
    {
        img : require("./assets/esp2.png"),
        title:'Morroco Marrakech',
        desc :'5 Star hotel ',
        reveiw:4.75,
        price:110,
        date :'12-20 oct',
        },
        {
            img : require("./assets/eqp3.png"),
            title:'Malysia kuala Lumpor ',
            desc :'5 Star hotel ',
            reveiw:4.80,
            price:125,
            date :'1-8 oct',
            },
            {
                img : require("./assets/esp4.png"),
                title:'Maldives ',
                desc :'5 Star hotel ',
                reveiw:4.80,
                price:99,
                date :'11-17 oct',
                },
                {
                    img : require("./assets/milan.png"),
                    title:'Italy Milan ',
                    desc :'Stay at Mario ',
                    reveiw:4.80,
                    price:99,
                    date :'9-14 oct',
                    },
                    {
                        img : require("./assets/lyon.png"),
                        title:'France Lyon ',
                        desc :'Stay at Lucas ',
                        reveiw:4.80,
                        price:99,
                        date :'2-8 oct',
                        },
                        {
                            img : require("./assets/losangeles.png"),
                            title:'USA los Angeles',
                            desc :'Stay at fifi',
                            reveiw:4.80,
                            price:143,
                            date :'18-25 sep',
                            },
                            {
                                img : require("./assets/barcelona.png"),
                                title:'Spain barcelona',
                                desc :'Stay at Manuel',
                                reveiw:4.80,
                                price:33,
                                date :'24-1 oct',
                                },


]